sudo: false
dist: xenial  # Required for python 3.7
language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
cache:
    pip: true
install:
    - python3 setup.py install
    - pip install flake8 codecov coverage
script:
    - flake8
    - coverage run setup.py test
after_success:
    - codecov
