sudo: false
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
cache:
    pip: true
install:
    - python3 setup.py install
    - pip install flake8 codecov coverage
script:
    - flake8
    - coverage run setup.py test
after_success:
    - codecov
