site_name: Is Valid
repo_url: https://github.com/daanvdk/is_valid/
pages:
  - Home: index.md
  - Handbook:
    - Introduction: handbook/introduction.md
    - Installation: handbook/installation.md
    - Getting started: handbook/getting_started.md
  - Reference: reference.md
  - Changelog: changelog.md
  - About: about.md